# Render.com deployment configuration
services:
  - type: web
    name: campus-trading-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      # MONGO_URI - Set this in Render dashboard under Environment Variables
      # JWT_SECRET - Set this in Render dashboard under Environment Variables
